// <auto-generated />
using System;
using EasyBudget.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasyBudget.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EasyBudget.Data.Models.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Created = new DateTime(2023, 5, 9, 13, 59, 1, 695, DateTimeKind.Local).AddTicks(369),
                            Name = "Transport",
                            Type = 2,
                            Updated = new DateTime(2023, 5, 9, 13, 59, 1, 695, DateTimeKind.Local).AddTicks(379)
                        },
                        new
                        {
                            Id = 2L,
                            Created = new DateTime(2023, 5, 9, 13, 59, 1, 695, DateTimeKind.Local).AddTicks(380),
                            Name = "Food",
                            Type = 2,
                            Updated = new DateTime(2023, 5, 9, 13, 59, 1, 695, DateTimeKind.Local).AddTicks(381)
                        },
                        new
                        {
                            Id = 3L,
                            Created = new DateTime(2023, 5, 9, 13, 59, 1, 695, DateTimeKind.Local).AddTicks(381),
                            Name = "Groceries",
                            Type = 2,
                            Updated = new DateTime(2023, 5, 9, 13, 59, 1, 695, DateTimeKind.Local).AddTicks(382)
                        },
                        new
                        {
                            Id = 4L,
                            Created = new DateTime(2023, 5, 9, 13, 59, 1, 695, DateTimeKind.Local).AddTicks(382),
                            Name = "Health",
                            Type = 2,
                            Updated = new DateTime(2023, 5, 9, 13, 59, 1, 695, DateTimeKind.Local).AddTicks(383)
                        },
                        new
                        {
                            Id = 5L,
                            Created = new DateTime(2023, 5, 9, 13, 59, 1, 695, DateTimeKind.Local).AddTicks(411),
                            Name = "Work",
                            Type = 2,
                            Updated = new DateTime(2023, 5, 9, 13, 59, 1, 695, DateTimeKind.Local).AddTicks(412)
                        },
                        new
                        {
                            Id = 6L,
                            Created = new DateTime(2023, 5, 9, 13, 59, 1, 695, DateTimeKind.Local).AddTicks(412),
                            Name = "Home",
                            Type = 2,
                            Updated = new DateTime(2023, 5, 9, 13, 59, 1, 695, DateTimeKind.Local).AddTicks(413)
                        },
                        new
                        {
                            Id = 7L,
                            Created = new DateTime(2023, 5, 9, 13, 59, 1, 695, DateTimeKind.Local).AddTicks(413),
                            Name = "Investments",
                            Type = 2,
                            Updated = new DateTime(2023, 5, 9, 13, 59, 1, 695, DateTimeKind.Local).AddTicks(414)
                        },
                        new
                        {
                            Id = 8L,
                            Created = new DateTime(2023, 5, 9, 13, 59, 1, 695, DateTimeKind.Local).AddTicks(414),
                            Name = "Others expenses",
                            Type = 2,
                            Updated = new DateTime(2023, 5, 9, 13, 59, 1, 695, DateTimeKind.Local).AddTicks(414)
                        },
                        new
                        {
                            Id = 9L,
                            Created = new DateTime(2023, 5, 9, 13, 59, 1, 695, DateTimeKind.Local).AddTicks(415),
                            Name = "Salary",
                            Type = 1,
                            Updated = new DateTime(2023, 5, 9, 13, 59, 1, 695, DateTimeKind.Local).AddTicks(415)
                        },
                        new
                        {
                            Id = 10L,
                            Created = new DateTime(2023, 5, 9, 13, 59, 1, 695, DateTimeKind.Local).AddTicks(416),
                            Name = "Investments",
                            Type = 1,
                            Updated = new DateTime(2023, 5, 9, 13, 59, 1, 695, DateTimeKind.Local).AddTicks(416)
                        },
                        new
                        {
                            Id = 11L,
                            Created = new DateTime(2023, 5, 9, 13, 59, 1, 695, DateTimeKind.Local).AddTicks(417),
                            Name = "Other incomes",
                            Type = 1,
                            Updated = new DateTime(2023, 5, 9, 13, 59, 1, 695, DateTimeKind.Local).AddTicks(417)
                        });
                });

            modelBuilder.Entity("EasyBudget.Data.Models.Movement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("Date");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Movements");
                });

            modelBuilder.Entity("EasyBudget.Data.Models.Movement", b =>
                {
                    b.HasOne("EasyBudget.Data.Models.Category", "Category")
                        .WithMany("Movements")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EasyBudget.Data.Models.Category", b =>
                {
                    b.Navigation("Movements");
                });
#pragma warning restore 612, 618
        }
    }
}
